### PR TITLE
GUI Improvements (URL in GUI + Masked Connect Code Input)

### PR DESCRIPTION
**Pull request by nzbr**
- URL can be set in GUI
- ~~Added a Config class that can persist data such as the entered URL~~
- Made Submit (now Connect) button respond to the Enter-key
- Connect Code Input box is now a MaskedTextBox and Connect can only be clicked if it contains 6 valid characters
- Set Tab order
    - URL -> Connect Code -> Submit -> ...

### CODE REVIEW

**Comment by CarbonNeuron** [comment]
Sorry for making a pull request on your fork. I only added a few things to it that I feel would make it better.

**Review by Stenlan — CHANGES_REQUESTED** [review]
Looks good overall, but I cannot accept this as-is. We want to keep separation between the forms and the sockets. You have put socket initialization into the form. If you want, you can use dependency injection instead, or make ClientSocket a singleton class and access it like that. I don't understand why you're using discard operators, but that might just be me. Lastly, could you provide a reason for changing our synchronous functions to async tasks? The design seemed fine as-is, and it was easier to call those functions from a synchronous context without messing with new thread creation outside of the function.

**Comment by Stenlan** [comment]
Thanks for addressing my points @nzbr (not sure how to tag here, sorry). I will review your changes again tomorrow

**Comment by nzbr** [comment]
I have now moved ClientSocket creation back into Program.cs
In `doConnect()` (UserForm.cs) `SendConnectCode()` is called directly after `Connect()`. The SocketIO socket connects asynchronously. Because of that I made Connect async, so that I could await `socket.ConnectAsync()` and then `Connect()` itself to make sure that the socket is actually connected when `SendConnectCode()` is called.
Another option to avoid the async entirely is to make `Connect()` accept a callback that would be added to the things executed in `socket.OnConnected`
`SendConnectCode()` didn't really need to be async, so I removed that.

As for the discards: VisualStudio complains if a function that returns a `Task` is called in an asynchronous context but not awaited. Explicitly discarding the Task was the fix VS recommended to me

**Comment by CarbonNeuron** [comment]
Pretty sure you can move the creation of the GameMemReader back to Program.cs because the sockets arent subscribed to the events until after they are connected. Maybe you could create a Public Event in ClientSocket that fires when the private socket's OnConnected event is fired? so you can know if they connected or not. Just some ideas.

**Comment by nzbr** [comment]
@Stenlan are you still interested in merging this PR or can I close it?

**Pull request merged**
