### PR TITLE
Rework of ProcessMemory for better cross-platform support.

### PR DESCRIPTION
**Pull request by TauAkiou**
While testing amonguscapture-gtk, I found that the current ProcessMemory class doesn't provide a particularly good framework for cross platform support. This update reworks the ProcessMemory class into a more modular design and further organizes all of the the memory-related classes into their own directory.

To do so, I did the following:

ProcessMemory has been split from a single static class into an abstract class (ProcessMemoryBase), which platform-specific ProcessMemory implementations derive from.

ProcessMemoryBase still supplies the same common interface from the original ProcessMemory, which allows every implementation of ProcessMemory inheriting from it to supply the same functionality. All new implementations will need to do is inherit ProcessMemoryBase, override all necessary methods, and initialize itself in GameMemReader.

The naming convention for ProcessMemory children classes is "ProcessMemoryPlatform", such as ProcessMemoryWindows, or ProcessMemoryLinux.

Changes to GameMemReader were necessary, but required no fundamental changes to the core processing loop. ProcessMemory is now a member of GameMemReader, which now initializes the correct instance during initialization. New ProcessMemoryPlatform instances should be initialized in the constructor, and if a platform is not supported, a 'NotImplementedException' is currently thrown.

In the event that a class outside GameMemReader needs to access a public method of ProcessMemoryBase, public methods for certain calls (currently only GetStringFromMemory()) are provided. 

This is currently viable since the only PC version of Among Us available is the Windows release, which runs through Linux (and potentially MacOS and other .NET supported platforms) through Wine (https://www.protondb.com/app/945360). As dotnet is flaky under Wine, this allows for native implementations of the ProcessMemory code to operate and let people playing on alternate OS to play with and attach to the amongusdiscord bot.

If InnerSloth ever releases native clients for other platforms, it is likely possible that this will have to be revisited but since we only currently have a Windows client, this is not an issue.

### CODE REVIEW

**Comment by TauAkiou** [comment]
I have been continuously testing the ProcessMemoryLinux module, and I believe at this point it is ready for deployment. If you want to include that module in master, I can either include it with this pull request, or create a second pull request for further review.

It's worth also stressing that ProcessMemoryLinux will not actually make the master branch support Linux, as Linux doesn't and probably won't ever support WinForms outside of Mono (hence the existence my gtk fork) However, this does provide a working memory backend for Linux platforms that would be helpful for anyone seeking to make their own fork.

**Comment by TauAkiou** [comment]
I rebased the code to the latest master - the base branch switches are to update the github commit log to remove irrelevant commits that showed up from the rebase.

I also added Jetbrains ignores to the .gitignore to keep Jetbrains Rider files from being pushed to remote.

**Comment by Stenlan** [comment]
I have merged this into a new branch called 'multiplatform'. Thanks very much for your efforts. I'm going to make a few slight changes to the structure to keep low coupling between the gamememreader and the processmemory classes, then merge it into master.

**Comment by Stenlan** [comment]
Take a look at the changes I've made to the multiplatform branch. It's not much, but I think they're important structural changes. I have removed coupling between ProcessMemory and GameMemReader, because I don't want them to be dependent upon each other. This also means that PlayerInfo (and other classes) can just call ProcessMemory directly, instead of having to go through GameMemReader, which would be bad design. I also dislike the -Base suffix, so I have removed this. The creational method is now merged within ProcessMemory, which I have made a singleton. Feel free to leave feedback here, and once again thanks for your contribution

**Comment by TauAkiou** [comment]
It looks fine to me - the initial design was what made sense to me at the time. As long as the code conforms to how you want it to conform, that's good enough.

**Comment by murshid1988** [comment]
So I can run this in Ubuntu now?

**Comment by CarbonNeuron** [comment]
> So I can run this in Ubuntu now? 

No absolutely not. Among us doesn't even run in Ubuntu. Ontop of the fact our GUI is written in WinForms that only works on windows.

**Comment by TauAkiou** [comment]
@murshid1988

For Linux support, use my fork: https://github.com/TauAkiou/amonguscapture-gtk. Remember to use the 'linux-mem-new' branch.

I've been using it with my Discord games for awhile, and it's worked quite well.

You may have to build it yourself for best results. The pre-compiled releases I posted seem to have weird bugs.

@CarbonNeuron 

Among Us does play perfectly in Wine, so it does run under Linux quite well. I've been playing it like this for quite awhile. 

Speaking of which, when is the 'crossplatform' branch going to be merged? I'd like to merge my Linux support branch to my project's master and integrate all of the features and fixes that the latest releases have, but I'm still waiting for master to have the crossplatform code to do that.

**Comment by murshid1988** [comment]
> > So I can run this in Ubuntu now?
> 
> No absolutely not. Among us doesn't even run in Ubuntu. Ontop of the fact our GUI is written in WinForms that only works on windows.

FYI I play Among Us in Ubuntu and it works without any issues. All I had to do was forcing it to use Proton 4.11-13 in Steam.

**Comment by murshid1988** [comment]
> @murshid1988
> 
> For Linux support, use my fork: https://github.com/TauAkiou/amonguscapture-gtk. Remember to use the 'linux-mem-new' branch.
> 
> I've been using it with my Discord games for awhile, and it's worked quite well.
> 
> You may have to build it yourself for best results. The pre-compiled releases I posted seem to have weird bugs.
> 
> Also keep in mind that it's currently out of date - I'm waiting on the multiplatform code to hit master before I continue updating the project.
> 
> @CarbonNeuron
> 
> Among Us does play perfectly in Wine, so it does run under Linux quite well.
> 
> Speaking of which, when is the 'multiplatform' branch going to be merged? I'd like to merge my Linux support branch to my project's master and integrate all of the features and fixes that the latest releases have in the primary branch, but I'm still waiting for master to have the crossplatform code to do that.

Thank you. I will take a look at it and let you know

**Pull request merged**
